[package]
name = "utils"
version = "0.8.1-master"
authors = ["Leonardo Gibrowski Faé <leonardo.fae44@gmail.com>"]
edition = "2021"

[dependencies]
lazy_static = "1.4"
lzzzz = "=1.0.4"
rkyv.version = "0.7"
rkyv.features = ["strict", "validation"]

[dev-dependencies]
rand = "0.8"
criterion = "0.5"

[[bench]]
name = "compression"
harness = false
